# Generated by Django 6.0.3 on 2026-03-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='alert_type',
            field=models.CharField(choices=[('normal', 'Норма'), ('warning', 'Предупреждение'), ('danger', 'Тревога')], default='normal', max_length=10),
        ),
    ]
